### ISSUE TITLE
Example home.ui and other crash because of incorrect file path string appending

### ISSUE THREAD

**Issue by mennodoor** [slaclab/pydm#32]
Hello,
I just started with pydm and want to try out a few of the shipped examples. Problem is: when I start python.exe pydm.py examples/home.ui the home-ui will open but every button click will result in a python crash with the following error:

``` 
Traceback (most recent call last):
  File "E:\pydm_testing\pydm\widgets\related_display_button.py", line 54, in mouseReleaseEvent
    self.open_display()
  File **"E:\pydm_testing\pydm\widgets\related_display_button.py",** line 65, in open_display
    self.window().go(self.displayFilename, macros=macros)
  File "E:\pydm_testing\pydm\main_window.py", line 96, in go
    self.open_file(ui_file, macros, command_line_args)
  File "E:\pydm_testing\pydm\main_window.py", line 66, in open_file
    self.open_abs_file(filename, macros, command_line_args)
  File "E:\pydm_testing\pydm\main_window.py", line 69, in open_abs_file
    widget = self.app.open_file(filename, macros, command_line_args)
  File "E:\pydm_testing\pydm\application.py", line 164, in open_file
    widget = self.load_ui_file(filepath, macros)
  File "E:\pydm_testing\pydm\application.py", line 144, in load_ui_file
    return uic.loadUi(f)
  File "C:\Program Files\Python35\lib\site-packages\PyQt5\uic\__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\Program Files\Python35\lib\site-packages\PyQt5\uic\Loader\loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "C:\Program Files\Python35\lib\site-packages\PyQt5\uic\uiparser.py", line 1003, in parse
    document = parse(filename)
  File "C:\Program Files\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Program Files\Python35\lib\xml\etree\ElementTree.py", line 585, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'examplesimage_view/many_images.ui'
```

The last line shows the error: there is no slash after examples/ -> file not found...
I tried to alter the home.ui by adding a slash in front of image_view but then its leaving the "example" and its also not working...

Did I do something wrong? Is it a bug? Did I miss something while installing all the requiered packages? I tried it with python 3.5 and 3.6...

Thanks in advance,
piuu

**Comment by mattgibbs** [comment]
Hi Piuu, congratulations on probably being the first person to try running PyDM on Windows!  I think you are right, this is some sort of bug where the path to a file isn't being joined together correctly.  I'll look into it.
