### ISSUE TITLE
PyDMWaveformPlot crashes with Zeros Array

### ISSUE THREAD

**Issue by hhslepicka** [slaclab/pydm#324]
@marciodo reported that while testing the BLEN app and some error messages started to show on the console.
I tried to test with the latest version from master and I can confirm the issue.
We also need to check if the same will happen for the other types of plot that we have in store.

```python
Traceback (most recent call last):
  File "/u/re/slepicka/PYDM_TEST/pydm-git/pydm/widgets/waveformplot.py", line 424, in redrawPlot
    self.updateAxes()
  File "/u/re/slepicka/PYDM_TEST/pydm-git/pydm/widgets/waveformplot.py", line 404, in updateAxes
    (curve_ymin, curve_ymax)) = curve.limits()
  File "/u/re/slepicka/PYDM_TEST/pydm-git/pydm/widgets/waveformplot.py", line 243, in limits
    yspan = (float(np.amax(self.y_waveform)) -
  File "/afs/slac.stanford.edu/u/re/slepicka/local/mc/envs/py36/lib/python3.6/site-packages/numpy-1.14.2-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py", line 2320, in amax
    out=out, **kwargs)
  File "/afs/slac.stanford.edu/u/re/slepicka/local/mc/envs/py36/lib/python3.6/site-packages/numpy-1.14.2-py3.6-linux-x86_64.egg/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by hhslepicka** [comment]
Here is what happened:

```python
In [1]: import numpy as np

In [2]: x = np.array([])

In [3]: np.amax(x)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-e683349cd4a4> in <module>()
----> 1 np.amax(x)

~/mc/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims)
   2270
   2271     return _methods._amax(a, axis=axis,
-> 2272                           out=out, **kwargs)
   2273
   2274

~/mc/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py in _amax(a, axis, out, keepdims)
     24 # small reductions
     25 def _amax(a, axis=None, out=None, keepdims=False):
---> 26     return umr_maximum(a, axis, None, out, keepdims)
     27
     28 def _amin(a, axis=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation maximum which has no identity
```
