### ISSUE TITLE
PyDMWaveformPlot crashes with a not initialized waveform

### ISSUE THREAD

**Issue by marciodo** [slaclab/pydm#362]
Put a PyDMWaveformPlot on a form and use as channel a PV to a waveform in a UDF Invalid state (NORD = 0, by the way). I tried it only in EPICS 3.

Once you run the form, it crashes with:

QXcbConnection: XCB error: 148 (Unknown), sequence: 174, resource id: 0, major code: 140 (Unknown), minor code: 20
Traceback (most recent call last):
  File "/afs/slac/g/lcls/package/python/python2.7.9/linux-x86_64/lib/python2.7/site-packages/pydm/widgets/waveformplot.py", line 425, in redrawPlot
    self.updateAxes()
  File "/afs/slac/g/lcls/package/python/python2.7.9/linux-x86_64/lib/python2.7/site-packages/pydm/widgets/waveformplot.py", line 405, in updateAxes
    (curve_ymin, curve_ymax)) = curve.limits()
  File "/afs/slac/g/lcls/package/python/python2.7.9/linux-x86_64/lib/python2.7/site-packages/pydm/widgets/waveformplot.py", line 243, in limits
    yspan = (float(np.amax(self.y_waveform)) -
  File "/afs/slac/g/lcls/package/python/python2.7.9/linux-x86_64/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2320, in amax
    out=out, **kwargs)
  File "/afs/slac/g/lcls/package/python/python2.7.9/linux-x86_64/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
Aborted

I also opened the screen with a filled waveform and it worked well. But when I restarted the IOC, the form crashed again.

**Comment by hhslepicka** [comment]
Thank you, Márcio!

I guess this one is fixed at the latest tag but t is not yet deployed at
development.
I will look into that and confirm.

**Comment by hhslepicka** [comment]
Duplicated of #324 .
