### ISSUE TITLE
How to create a window without the PyDMApplication bar?

### ISSUE THREAD

**Issue by mennodoor** [slaclab/pydm#42]
Hi,
is it possible to use pydm without the standard top bar? I didn't found an easy way to get rid of it... for some it may be usefull but especially on my system (Windows) all button clicks result in a python crash.
Thanks!
piuu

**Comment by mattgibbs** [comment]
Currently, there is no way to remove the bar.  Can you give me the error message Python says when it crashes?  And it's really when you click any of the menu items?

--Matt

**Comment by piuupiuupiuu** [comment]
Sorry, its not all its just the "Go"-Button. 

this is the error when entering "timeplot.ui":
`
Traceback (most recent call last):
  File "E:\pydm\main_window.py", line 90, in go_button_pressed
    self.go(filename)
  File "E:\pydm\main_window.py", line 96, in go
    self.open_file(ui_file, macros, command_line_args)
  File "E:\pydm\main_window.py", line 66, in open_file
    self.open_abs_file(filename, macros, command_line_args)
  File "E:\pydm\main_window.py", line 69, in open_abs_file
    widget = self.app.open_file(filename, macros, command_line_args)
  File "E:\pydm\application.py", line 164, in open_file
    widget = self.load_ui_file(filepath, macros)
  File "E:\pydm\application.py", line 144, in load_ui_file
    return uic.loadUi(f)
  File "C:\Program Files\Python36\lib\site-packages\PyQt5\uic\__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\Program Files\Python36\lib\site-packages\PyQt5\uic\Loader\loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "C:\Program Files\Python36\lib\site-packages\PyQt5\uic\uiparser.py", line 1003, in parse
    document = parse(filename)
  File "C:\Program Files\Python36\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "C:\Program Files\Python36\lib\xml\etree\ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'pydmtimeplot.ui'
`
This when entering "gibberish":
`
Traceback (most recent call last):
  File "E:\pydm\main_window.py", line 90, in go_button_pressed
    self.go(filename)
  File "E:\pydm\main_window.py", line 96, in go
    self.open_file(ui_file, macros, command_line_args)
  File "E:\pydm\main_window.py", line 66, in open_file
    self.open_abs_file(filename, macros, command_line_args)
  File "E:\pydm\main_window.py", line 69, in open_abs_file
    widget = self.app.open_file(filename, macros, command_line_args)
  File "E:\pydm\application.py", line 168, in open_file
    raise Exception("invalid file type: {}".format(extension))
Exception: invalid file type:
`

Thanks for answering so quickly!

**Comment by hhslepicka** [comment]
@mennodoor I have a fix for the Go button issue.
I'm cleaning up and will submit a PR to address this.
