### ISSUE TITLE
Error when starting python pydm.py pythonui.py on Windows(?)

### ISSUE THREAD

**Issue by mennodoor** [slaclab/pydm#45]
Hi all,
i tried to run a converted .py file with pydm and it got some error in the `load_py_file`-function in `pydm/application.py`:

```
Traceback (most recent call last):
  File "pydm.py", line 20, in <module>
    app = PyDMApplication(ui_file=pydm_args.displayfile, command_line_args=pydm_args.display_args, perfmon=pydm_args.perfmon, macros=macros)
  File "E:\pydm\pydm\application.py", line 67, in __init__
    self.make_window(ui_file, macros, command_line_args)
  File "E:\pydm\pydm\application.py", line 129, in make_window
    main_window.open_file(ui_file, macros, command_line_args)
  File "E:\pydm\pydm\main_window.py", line 66, in open_file
    self.open_abs_file(filename, macros, command_line_args)
  File "E:\pydm\pydm\main_window.py", line 69, in open_abs_file
    widget = self.app.open_file(filename, macros, command_line_args)
  File "E:\pydm\pydm\application.py", line 167, in open_file
    widget = self.load_py_file(filepath, args)
  File "E:\pydm\pydm\application.py", line 154, in load_py_file
    return module.intelclass(args=args)
AttributeError: module 'intelclass' has no attribute 'intelclass'
```

Somehow the module `module` is already the `intelclass`?
Thanks for you help,
menno

**Comment by mattgibbs** [comment]
Wow, that error message is hard to decipher!  I'll have to improve it.  I believe the problem is that your .py file doesn't specify a variable called 'intelclass'.  When PyDM loads a python file, it looks for a variable called 'intelclass' that points to the Display subclass you want to run - otherwise, if you had multiple classes in the same file, PyDM wouldn't know which one you want to launch.

For example, if your class is called "MyNewDisplay", do something like this:
```from pydm import Display
class MyNewDisplay(Display):
  //All your code goes in here...

intelclass = MyNewDisplay
```

This system is kind of clunky.  Maybe I could find a way to load the file, and always use the first Display subclass found.  I don't think there are any reasons to have multiple Display subclasses in the same file.

**Comment by mennodoor** [comment]
Hi!
thanks for the help and the fix! Unfortunately it does not work with my example or with the pydm supplied examples.

** My example: **
```
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 57)
        MainWindow.setMaximumSize(QtCore.QSize(400, 70))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.PyDMLabel = PyDMLabel(self.centralwidget)
        self.PyDMLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.PyDMLabel.setToolTip("")
        self.PyDMLabel.setWhatsThis("")
        self.PyDMLabel.setObjectName("PyDMLabel")
        self.gridLayout.addWidget(self.PyDMLabel, 1, 0, 1, 1)
       self.gridLayout.addWidget(self.PyDMLabel, 1, 0, 1, 1)
        self.PyDMLabel_2 = PyDMLabel(self.centralwidget)
        self.PyDMLabel_2.setMinimumSize(QtCore.QSize(80, 0))
        self.PyDMLabel_2.setToolTip("")
        self.PyDMLabel_2.setWhatsThis("")
        self.PyDMLabel_2.setObjectName("PyDMLabel_2")
        self.gridLayout.addWidget(self.PyDMLabel_2, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.PyDMSpinbox = PyDMSpinbox(self.centralwidget)
        self.PyDMSpinbox.setMinimumSize(QtCore.QSize(200, 0))
        self.PyDMSpinbox.setToolTip("")
        self.PyDMSpinbox.setWhatsThis("")
        self.PyDMSpinbox.setObjectName("PyDMSpinbox")
        self.gridLayout.addWidget(self.PyDMSpinbox, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

from pydm.widgets.label import PyDMLabel
from pydm.widgets.spinbox import PyDMSpinbox
```

** Error Message (python pydm.py example.py): **
```
Traceback (most recent call last):
  File "pydm.py", line 20, in <module>
    app = PyDMApplication(ui_file=pydm_args.displayfile, command_line_args=pydm_args.display_args, perfmon=pydm_args.perfmon, macros=macros)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 70, in __init__
    self.make_window(ui_file, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 132, in make_window
    main_window.open_file(ui_file, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/main_window.py", line 66, in open_file
    self.open_abs_file(filename, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/main_window.py", line 69, in open_abs_file
    widget = self.app.open_file(filename, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 195, in open_file
    widget = self.load_py_file(filepath, args)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 167, in load_py_file
    raise ValueError("Invalid File Format. {} has no class inheriting from Display. Nothing to open at this time.".format(pyfile))
ValueError: Invalid File Format. quadrupole_design.py has no class inheriting from Display. Nothing to open at this time.
```

When I **change the class definition** to `class Ui_MainWindow(Display):` and add `from pydm.display_module import Display` the following error raises:
```
Traceback (most recent call last):
  File "pydm.py", line 20, in <module>
    app = PyDMApplication(ui_file=pydm_args.displayfile, command_line_args=pydm_args.display_args, perfmon=pydm_args.perfmon, macros=macros)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 70, in __init__
    self.make_window(ui_file, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 132, in make_window
    main_window.open_file(ui_file, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/main_window.py", line 66, in open_file
    self.open_abs_file(filename, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/main_window.py", line 69, in open_abs_file
    widget = self.app.open_file(filename, macros, command_line_args)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 195, in open_file
    widget = self.load_py_file(filepath, args)
  File "/home/menno/git_repos/pydm/pydm/application.py", line 180, in load_py_file
    return cls(args=args)
  File "/home/menno/git_repos/pydm/pydm/display_module.py", line 9, in __init__
    self.load_ui(parent=parent)
  File "/home/menno/git_repos/pydm/pydm/display_module.py", line 20, in load_ui
    self.ui = uic.loadUi(self.ui_filepath(), baseinstance=self)
  File "/home/menno/git_repos/pydm/pydm/display_module.py", line 12, in ui_filepath
    raise NotImplementedError
NotImplementedError
```

**Comment by mennodoor** [comment]
Ok sorry for this! I did a lot of mistakes... The example is total nonsense, don't convert the .ui to .py just create a base-class:

```
import epics
import time
from pydm.PyQt import uic
from pydm.PyQt.QtCore import QObject, pyqtSlot, pyqtSignal
from pydm.PyQt.QtGui import QWidget
from os import path
from pydm import Display

class BeamlineApp(Display):
    def __init__(self, parent=None, args=None):
        super(BeamlineApp, self).__init__(parent=parent, args=args)

    @property
    def display_manager_window(self):
        return self.window()

    def ui_filename(self):
        return 'maingui_widget.ui'

    def ui_filepath(self):
        pp = path.join(path.dirname(path.realpath(__file__)), self.ui_filename())
        print("Path", pp)
        return pp

intelclass = BeamlineApp
```

One other mistake though: the .ui files should be Widgets and not MainWindows...

Thanks for the help!
menno

**Comment by hhslepicka** [comment]
Hi @mennodoor ,
No problem at all! Thanks for the feedback! This will guide us towards better documentation.

**Comment by mattgibbs** [comment]
I'm writing up a guide to writing script-based displays today, and I'll incorporate the problems you found.  We really appreciate these bug reports, keep them coming!
