### ISSUE TITLE
** WARNING Factory failed to create  "PyDMImageView"

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#610]
**Describe the bug**
On starting Qt Designer, this error is reported to the console:

```
(pydm_03) jemian@wow ~/.../projects/sbc-mako $ designer &
[3] 27778
(pydm_03) jemian@wow ~/.../projects/sbc-mako $ Loading PyDM Widgets
Exception occurred while running Qt Designer.
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/beams1/JEMIAN/Documents/projects/pydm-prj/pydm/widgets/qtplugin_base.py", line 116, in createWidget
    w = self.cls(parent=parent)
  File "/home/beams1/JEMIAN/Documents/projects/pydm-prj/pydm/widgets/image.py", line 109, in __init__
    ImageView.__init__(self, parent, view=plot_item)
  File "/home/beams/JEMIAN/.conda/envs/pydm_03/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 130, in __init__
    self.ui.setupUi(self)
  File "/home/beams/JEMIAN/.conda/envs/pydm_03/lib/python3.7/site-packages/pyqtgraph/imageview/ImageViewTemplate_pyqt5.py", line 133, in setupUi
    QtCore.QMetaObject.connectSlotsByName(Form)
SystemError: <built-in function connectSlotsByName> returned a result with an error set

Designer: The custom widget factory registered for widgets of class PyDMImageView returned 0.
** WARNING Factory failed to create  "PyDMImageView"
```

This warning is reported immediately on startup, before selecting create/open/....

**Expected behavior**
A quiet startup (no console output, no warnings)

**Steps to Reproduce**
1. `conda create -n pydm_demo -y python=3.7 pydm -c pydm-tag -c conda-forge`
1. `conda activate pydm_demo`
1. `designer &`

<details>

```
(base) jemian@wow ~ $ conda create -n pydm_demo -y python=3.7 pydm -c pydm-tag -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/beams/JEMIAN/.conda/envs/pydm_demo

  added / updated specs:
    - pydm
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    epicscorelibs-7.0.3.99.2.0 |   py37h68659b9_0         3.6 MB  conda-forge
    freetype-2.10.1            |       he06d7ca_0         877 KB  conda-forge
    icu-64.2                   |       he1b5a44_1        12.6 MB  conda-forge
    libiconv-1.15              |    h516909a_1006         2.0 MB  conda-forge
    libpng-1.6.37              |       hed695b0_1         308 KB  conda-forge
    pyepics-3.4.1              |           py37_0         183 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        19.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py37hc8dfbb8_1
  cffi               conda-forge/linux-64::cffi-1.14.0-py37hd463f26_0
  chardet            conda-forge/linux-64::chardet-3.0.4-py37hc8dfbb8_1006
  cryptography       conda-forge/linux-64::cryptography-2.8-py37hb09aad4_2
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  epicscorelibs      conda-forge/linux-64::epicscorelibs-7.0.3.99.2.0-py37h68659b9_0
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.1-he06d7ca_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.58.3-py37he00f558_1003
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.5-h0935bb2_2
  gstreamer          conda-forge/linux-64::gstreamer-1.14.5-h36ae1b5_2
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  idna               conda-forge/noarch::idna-2.9-py_1
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_0
  libblas            conda-forge/linux-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-16_openblas
  libclang           conda-forge/linux-64::libclang-9.0.1-default_hde54327_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_5
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006
  liblapack          conda-forge/linux-64::liblapack-3.8.0-16_openblas
  libllvm9           conda-forge/linux-64::libllvm9-9.0.1-hc9558a2_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.9-h5ec1e0e_0
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_1
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxkbcommon       conda-forge/linux-64::libxkbcommon-0.10.0-he1b5a44_0
  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0
  llvm-openmp        conda-forge/linux-64::llvm-openmp-9.0.1-hc9558a2_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  nspr               conda-forge/linux-64::nspr-4.25-he1b5a44_0
  nss                conda-forge/linux-64::nss-3.47-he751ad9_0
  numpy              conda-forge/linux-64::numpy-1.18.1-py37h95a1406_0
  openssl            conda-forge/linux-64::openssl-1.1.1e-h516909a_0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  pip                conda-forge/noarch::pip-20.0.2-py_2
  psutil             conda-forge/linux-64::psutil-5.7.0-py37h8f50634_1
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pycparser          conda-forge/noarch::pycparser-2.20-py_0
  pydm               pydm-tag/noarch::pydm-1.8.0-py_0
  pyepics            conda-forge/linux-64::pyepics-3.4.1-py37_0
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pyqt               conda-forge/linux-64::pyqt-5.12.3-py37hcca6a23_1
  pyqtgraph          conda-forge/noarch::pyqtgraph-0.11.0rc0-py_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py37hc8dfbb8_1
  python             conda-forge/linux-64::python-3.7.6-h357f687_4_cpython
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  qt                 conda-forge/linux-64::qt-5.12.5-hd8c4c69_1
  qtpy               conda-forge/noarch::qtpy-1.9.0-py_0
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  requests           conda-forge/noarch::requests-2.23.0-pyh8c360ce_2
  scipy              conda-forge/linux-64::scipy-1.4.1-py37h921218d_0
  setuptools         conda-forge/linux-64::setuptools-46.0.0-py37hc8dfbb8_2
  six                conda-forge/noarch::six-1.14.0-py_1
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  urllib3            conda-forge/linux-64::urllib3-1.25.7-py37hc8dfbb8_1
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006



Downloading and Extracting Packages
epicscorelibs-7.0.3. | 3.6 MB    | ############################################################################################################### | 100% 
pyepics-3.4.1        | 183 KB    | ############################################################################################################### | 100% 
icu-64.2             | 12.6 MB   | ############################################################################################################### | 100% 
freetype-2.10.1      | 877 KB    | ############################################################################################################### | 100% 
libpng-1.6.37        | 308 KB    | ############################################################################################################### | 100% 
libiconv-1.15        | 2.0 MB    | ############################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pydm_demo
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) jemian@wow ~ $ conda activate pydm_demo
(pydm_demo) jemian@wow ~ $ designer &
[1] 5350
(pydm_demo) jemian@wow ~ $ Exception occurred while running Qt Designer.
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/beams/JEMIAN/.conda/envs/pydm_demo/lib/python3.7/site-packages/pydm/widgets/qtplugin_base.py", line 114, in createWidget
    w = self.cls(parent=parent)
  File "/home/beams/JEMIAN/.conda/envs/pydm_demo/lib/python3.7/site-packages/pydm/widgets/image.py", line 109, in __init__
    ImageView.__init__(self, parent, view=plot_item)
  File "/home/beams/JEMIAN/.conda/envs/pydm_demo/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 130, in __init__
    self.ui.setupUi(self)
  File "/home/beams/JEMIAN/.conda/envs/pydm_demo/lib/python3.7/site-packages/pyqtgraph/imageview/ImageViewTemplate_pyqt5.py", line 133, in setupUi
    QtCore.QMetaObject.connectSlotsByName(Form)
SystemError: <built-in function connectSlotsByName> returned a result with an error set

Designer: The custom widget factory registered for widgets of class PyDMImageView returned 0.
** WARNING Factory failed to create  "PyDMImageView"

```

</details>

**Possible Solution**
?

**My Platform**
```
(pydm_03) jemian@wow ~/.../projects/sbc-mako $ more /etc/os-release 
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Workstation"
VARIANT_ID="workstation"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"


REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

**Comment by hhslepicka** [comment]
@prjemian you need to lock Python to `=3.7.3` there is a bug that got fixed with PyQt 5.13.1 related to that and it affects Python 3.7.4 and higher.

**Comment by hhslepicka** [comment]
It is a duplicate of https://github.com/slaclab/pydm/issues/533

**Comment by prjemian** [comment]
Looked for `PyDMImageView` in the issue search and did not see that issue.  I'll try this now.  Mark this issue as duplicate.  Don't close this until I post confirmation.

**Comment by prjemian** [comment]
*Mea Culpa* (#582 was in the closed list, **got** to have better eyes and less multi-tasking)

**Comment by prjemian** [comment]
Success!

<details>

```
(base) jemian@wow ~ $ conda create -n pydm_demo -y python=3.7.3 pydm -c pydm-tag -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/beams/JEMIAN/.conda/envs/pydm_demo

  added / updated specs:
    - pydm
    - python=3.7.3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h516909a_2         396 KB  conda-forge
    python-3.7.3               |       h357f687_2        35.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        35.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py37hc8dfbb8_1
  cffi               conda-forge/linux-64::cffi-1.14.0-py37hd463f26_0
  chardet            conda-forge/linux-64::chardet-3.0.4-py37hc8dfbb8_1006
  cryptography       conda-forge/linux-64::cryptography-2.8-py37hb09aad4_2
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  epicscorelibs      conda-forge/linux-64::epicscorelibs-7.0.3.99.2.0-py37h68659b9_0
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.1-he06d7ca_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.58.3-py37he00f558_1003
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.5-h0935bb2_2
  gstreamer          conda-forge/linux-64::gstreamer-1.14.5-h36ae1b5_2
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  idna               conda-forge/noarch::idna-2.9-py_1
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_0
  libblas            conda-forge/linux-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-16_openblas
  libclang           conda-forge/linux-64::libclang-9.0.1-default_hde54327_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_5
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006
  liblapack          conda-forge/linux-64::liblapack-3.8.0-16_openblas
  libllvm9           conda-forge/linux-64::libllvm9-9.0.1-hc9558a2_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.9-h5ec1e0e_0
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_1
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxkbcommon       conda-forge/linux-64::libxkbcommon-0.10.0-he1b5a44_0
  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0
  llvm-openmp        conda-forge/linux-64::llvm-openmp-9.0.1-hc9558a2_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  nspr               conda-forge/linux-64::nspr-4.25-he1b5a44_0
  nss                conda-forge/linux-64::nss-3.47-he751ad9_0
  numpy              conda-forge/linux-64::numpy-1.18.1-py37h95a1406_0
  openssl            conda-forge/linux-64::openssl-1.1.1e-h516909a_0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  pip                conda-forge/noarch::pip-20.0.2-py_2
  psutil             conda-forge/linux-64::psutil-5.7.0-py37h8f50634_1
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pycparser          conda-forge/noarch::pycparser-2.20-py_0
  pydm               pydm-tag/noarch::pydm-1.8.0-py_0
  pyepics            conda-forge/linux-64::pyepics-3.4.1-py37_0
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pyqt               conda-forge/linux-64::pyqt-5.12.3-py37hcca6a23_1
  pyqtgraph          conda-forge/noarch::pyqtgraph-0.11.0rc0-py_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py37hc8dfbb8_1
  python             conda-forge/linux-64::python-3.7.3-h357f687_2
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  qt                 conda-forge/linux-64::qt-5.12.5-hd8c4c69_1
  qtpy               conda-forge/noarch::qtpy-1.9.0-py_0
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  requests           conda-forge/noarch::requests-2.23.0-pyh8c360ce_2
  scipy              conda-forge/linux-64::scipy-1.4.1-py37h921218d_0
  setuptools         conda-forge/linux-64::setuptools-46.0.0-py37hc8dfbb8_2
  six                conda-forge/noarch::six-1.14.0-py_1
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  urllib3            conda-forge/linux-64::urllib3-1.25.7-py37hc8dfbb8_1
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006



Downloading and Extracting Packages
python-3.7.3         | 35.3 MB   | ############################################################################################################### | 100% 
bzip2-1.0.8          | 396 KB    | ############################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pydm_demo
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) jemian@wow ~ $ conda activate pydm_demo
(pydm_demo) jemian@wow ~ $ designer &
[1] 13277
(pydm_demo) jemian@wow ~ $ 
```
</details>

**Comment by prjemian** [comment]
I'll close now.

**Comment by prjemian** [comment]
Note:  *After* creating the conda environment, need to **pin** python to 3.7.3 to prevent upgrades.

**Comment by hhslepicka** [comment]
@prjemian I will follow up with the `pyqtgraph` folks and see if they are close to an official release. Last that I checked, using their `develop` branch solved this issue but I need to look at it again. I will assign the original issue to me and look into that in the following days after looking at your PRs! 😉

**Comment by prjemian** [comment]
documentation about how to add the pin:  https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning

Apparently no conda command-line option.  Could `cat` that into the file or some other creative UNIX command line (such as echo and tee).

**Comment by prjemian** [comment]
With the conda environment activated, this line adds the required pin:

    echo "python ==3.7.3" | tee -a ${CONDA_PREFIX}/conda-meta/pinned
