### ISSUE TITLE
Right clicking PyDMEnumComboBox causes eventFilter failure

### ISSUE THREAD

**Issue by klauer** [slaclab/pydm#682]
**Describe the bug**
```
Traceback (most recent call last):
  File "/Users/klauer/docs/Repos/pydm/pydm/widgets/base.py", line 1073, in eventFilter
    return PyDMWidget.eventFilter(self, obj, event)
  File "/Users/klauer/docs/Repos/pydm/pydm/widgets/base.py", line 657, in eventFilter
    if event.button() == Qt.MiddleButton:
AttributeError: 'QContextMenuEvent' object has no attribute 'button'
```

**Expected behavior**
No exception

**Steps to Reproduce**
* Display with `PyDMComboBox`
* Right-click it, see
```
Traceback (most recent call last):
  File "/Users/klauer/docs/Repos/pydm/pydm/widgets/base.py", line 1073, in eventFilter
    return PyDMWidget.eventFilter(self, obj, event)
  File "/Users/klauer/docs/Repos/pydm/pydm/widgets/base.py", line 657, in eventFilter
    if event.button() == Qt.MiddleButton:
AttributeError: 'QContextMenuEvent' object has no attribute 'button'
```

**Additional context**

Latest pydm master.

**Comment by klauer** [comment]
I don't see a code path where the event filter would get a `QContextMenuEvent` masquerading as a `QMouseButtonPress` (these are distinct event types: https://doc.qt.io/qt-5/qevent.html#Type-enum) - but it did 🤷‍♂️

**Comment by hhslepicka** [comment]
I tried to reproduce it locally with a PyDM Combo and I could not get it to go bad...
Is it happening all the time for you? If yes, at the Mac of Linux?

**Comment by klauer** [comment]
Not reproducible; closing
