### ISSUE TITLE
CA PyDMLineEdit causes crash

### ISSUE THREAD

**Issue by rreno** [slaclab/pydm#703]
**Describe the bug**
Some PyDMLineEdit widgets will cause the screen to crash when text is entered. No text is written to the PV
Error message:
```
Traceback (most recent call last):
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/pydm/widgets/line_edit.py", line 96, in send_value
    num_value = self.channeltype(send_value)
TypeError: cannot create 'NoneType' instances

```

**Steps to Reproduce**
Open the BLEN engineering screens
    /u/cd/rreno/b084blen.bash &
    Click Bunch Length BZ21B Engineering Screens button on bottom right of display
    Choose the FPGA Configuration / Timing tab
    Try to enter text in either of the first two PyDMLineEdit widgets (Upload FPGA Config From: or YAML Root Node)

**My Platform**
lcls-dev3
PyDM v1.10.6
Python 2.7.9
Numpy 1.16.5
PyQT 5.9.2
Qt 5.9.5
PyQtGraph 0.10.0

The error occurs when tunneling X over ssh with MobaXTerm to my Windows machine and on FastX 3.

**Additional context**
I checked View -> Show Connections and all PVs appear to be connected as I would expect.

When navigating to the tab with the widgets causing the error the following stack trace is printed but the screen is otherwise usable.

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/ca.py", line 709, in _onMonitorEvent
    args.usr(value=value, **kwds)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 767, in __on_changes
    self.run_callbacks()
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 778, in run_callbacks
    self.run_callback(index)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 801, in run_callback
    fcn(**kwd)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/pydm/data_plugins/epics_plugins/pyepics_plugin_component.py", line 65, in send_new_value
    self.new_value_signal[int].emit(int(value))
TypeError: int() argument must be a string or a number, not 'c_ubyte_Array_1'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/ca.py", line 709, in _onMonitorEvent
    args.usr(value=value, **kwds)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 767, in __on_changes
    self.run_callbacks()
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 778, in run_callbacks
    self.run_callback(index)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 48, in wrapped
    return func(self, *args, **kwargs)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/epics/pv.py", line 801, in run_callback
    fcn(**kwd)
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/pydm/data_plugins/epics_plugins/pyepics_plugin_component.py", line 65, in send_new_value
    self.new_value_signal[int].emit(int(value))
TypeError: int() argument must be a string or a number, not 'c_ubyte_Array_1'

```

**Comment by hhslepicka** [comment]
Thanks for reporting that. I will take a look into it.

**Comment by hhslepicka** [comment]
From what I could find while investigating it, with Python 2.7 PyEPICS is returning a weird type that causes issues when we try to cast it. The same error doesn't happen with Python 3.

```python
In [1]: import epics

In [2]: pv_name = 'BLEN:BC2B:950:loadConfigRoot'

In [3]: def cb(value, *args, **kwargs):
   ...:     print('Callback with value: ', value, ' and type: ', type(value), ' | args: ', args, ' | kwargs: ', kwargs)
   ...:

In [4]: pv = epics.PV(pv_name, callback=cb)

In [5]: ('Callback with value: ', <epics.dbr.c_ubyte_Array_1 object at 0x7fefa82ebcb0>, ' and type: ', <class 'epics.dbr.c_ubyte_Array_1'>, ' | args: ', (), ' | kwargs: ', {'lower_disp_limit': None, 'nanoseconds': 58873842L, 'char_value': '', 'chid': 140668098084864, 'severity': 0, 'upper_ctrl_limit': None, 'read_access': True, 'access': 'read/write', 'ftype': 18, 'units': None, 'lower_ctrl_limit': None, 'write_access': True, 'type': 'time_char', 'pvname': 'BLEN:BC2B:950:loadConfigRoot', 'status': 0, ...})


In [5]: pv_name_2 = 'BLEN:BC2B:950:loadConfigFile'

In [6]: pv2 = epics.PV(pv_name_2, callback=cb)

In [7]: ('Callback with value: ', array([97,  0], dtype=uint8), ' and type: ', <type 'numpy.ndarray'>, ' | args: ', (), ' | kwargs: ', {'lower_disp_limit': None, 'nanoseconds': 75456117L, 'char_value': 'a', 'chid': 140668098084920, 'severity': 0, 'upper_ctrl_limit': ...})



$ cainfo BLEN:BC2B:950:loadConfigFile
BLEN:BC2B:950:loadConfigFile
    State:            connected
    Access:           read, write
    Native data type: DBF_CHAR
    Request type:     DBR_CHAR
    Element count:    256

$ cainfo BLEN:BC2B:950:loadConfigRoot
BLEN:BC2B:950:loadConfigRoot
    State:            connected
    Access:           read, write
    Native data type: DBF_CHAR
    Request type:     DBR_CHAR
    Element count:    256

$ caget BLEN:BC2B:950:loadConfigRoot BLEN:BC2B:950:loadConfigFile
BLEN:BC2B:950:loadConfigRoot 256 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
BLEN:BC2B:950:loadConfigFile 256 97 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
$
```

**Comment by hhslepicka** [comment]
Due to the fact that PyDM never received an event of the channel so it doesn't know its type to be able to properly cast the data from the lineEdit to the channel expected type and it causes the error below:
```
Traceback (most recent call last):
  File "/afs/slac/g/lcls/package/python/python2.7.9_bak/linux-x86_64/lib/python2.7/site-packages/pydm/widgets/line_edit.py", line 96, in send_value
    num_value = self.channeltype(send_value)
TypeError: cannot create 'NoneType' instances
```

I was able to reproduce both issues locally via a test database:
```
record(waveform, "BLEN:BC2B:950:loadConfigFile"){
	field(NELM, 256)
	field(FTVL, "CHAR")
}

record(waveform, "BLEN:BC2B:950:loadConfigRoot"){
	field(NELM, 256)
	field(FTVL, "CHAR")
}
```

Starting this ioc with: `softIoc -d test.db` works fine but if we start it and do a subsequent `caput PVNAME 0` it breaks with the errors above for Python 2.
