### ISSUE TITLE
timeplot: Exception: Scale 'left' not found.

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#841]
**Describe the bug**
When starting with a single PyDMTimePlot widget,  this exception is written to the console:

```bash
Traceback (most recent call last):
  File "/home/zorinvm/Apps/miniconda3/envs/dev-pydm/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 413, in updateGrid
    self.getAxis('left').setGrid(y)
  File "/home/zorinvm/Apps/miniconda3/envs/dev-pydm/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 1150, in getAxis
    self._checkScaleKey(name)
  File "/home/zorinvm/Apps/miniconda3/envs/dev-pydm/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 1142, in _checkScaleKey
    raise Exception("Scale '%s' not found. Scales are: %s" % (key, str(list(self.axes.keys()))))
Exception: Scale 'left' not found. Scales are: ['top', 'bottom', 'right']
Traceback (most recent call last):
  File "/home/zorinvm/Apps/miniconda3/envs/dev-pydm/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 413, in updateGrid
    self.getAxis('left').setGrid(y)
  File "/home/zorinvm/Apps/miniconda3/envs/dev-pydm/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 1150, in getAxis
    self._checkScaleKey(name)
  File "/home/zorinvm/Apps/miniconda3/envs/dev-pydm/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 1142, in _checkScaleKey
    raise Exception("Scale '%s' not found. Scales are: %s" % (key, str(list(self.axes.keys()))))
Exception: Scale 'left' not found. Scales are: ['top', 'bottom', 'right']
```

**Expected behavior**
No such exceptions from the PyDMTimePlot widget.

**Steps to Reproduce**
1. In designer, create a screen with a PyDMTimePlot widget and create one curve connecting to an EPICS PV.
2. Save the screen.
3. From bash, start pydm with the new screen.

**Possible Solution**
Not sure about that.

**My Platform**
Linux (Zorin) guest in a Windows 11 VirtualBox host.

Anaconda:

```
# Name                    Version                   Build  Channel
python                    3.9.12               h12debd9_0  
pydm                      1.15.1+4.g6a3379fa.dirty           dev_0    <develop>
pyqt                      5.12.3           py39hf3d152e_8    conda-forge
pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
pyqtgraph                 0.12.4             pyhd8ed1ab_0    conda-forge
pytest-qt                 4.0.2              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
qtpy                      2.0.1              pyhd3eb1b0_0  
```

and others

**Comment by prjemian** [comment]
@jbellister-slac : Indeed, thanks!

**Comment by klauer** [comment]
Following up on this issue reported during the codeathon - was this resolved somehow?

**Comment by prjemian** [comment]
not fixed yet
